### ISSUE TITLE
deprecated functions are broken

### ISSUE THREAD

**Issue by obfusk** [venthur/python-popcon#5]
It seems like the deprecated functions are broken; e.g.

```py
def source_package(*package_list):
    ...
    logger.warning(
            'source_package is deprecated, please use source_packages instead')
    return source_packages(*package_list) # <-- should be source_packages(package_list)

def source_packages(package_list):
    ...
```

**Comment by venthur** [comment]
Can you give me some more context about the expected behavior? I don't quite understand the issue yet. Thank you!

**Comment by obfusk** [comment]
There was a bug in the deprecated function: it called the new API with wrong arguments. IIRC correctly (sorry, it's been 3 years by now :smile:) this affected a script used by the reproducible builds tooling, which was fixed by using the new API.

I see the deprecated functions have been removed. So this is no longer an issue. Closing. Thanks!
