### ISSUE TITLE
PopCon Abandoned

### ISSUE THREAD

**Issue by ghost** [venthur/python-popcon#7]
If you're still about on GitHub, you may want to archive this repository, as PopCon has long since been abandoned by Canonical; they're not even hosting the database anymore. 😞

**Comment by venthur** [comment]
Popcon is still used on Debian, for which I originally developed it.

**Comment by ghost** [comment]
Hi, Venthur. In hindsight, it seems quite obvious and I should've checked first before posting. Thank you for responding and enjoy the rest of your day.
